### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by melwert** [robert461/web-2.0#1]
Was für Tools?

**Comment by robert461** [comment]
* [x] IDE festgelegt  
* [x] Front-Framework festgelegt
* [x] CSS-Framework festgelegt

**Comment by robert461** [comment]
IDE: IntelliJ, VS Code und Atom Editor
Frontend-Framework:
Backend-Framework:

**Comment by melwert** [comment]
- CSS-Framework: Bootstrap
- IDE: IntelliJ, VS Code, Atom
- Versuch PeerJS
- kein Frontend-Framework
